changes to prepare for production server
nnhsse202324/cte-web-admin pull request #16
Opened 2024-04-15 14:13 UTC by gcschmit

removed page/route that is no longer needed and moved logic to other routes

2024-04-16 13:44 UTC, panduh-s requested changes
Google Sign in is not working in this branch

2024-04-16 15:47 UTC, gcschmit commented
I reverted to the developer-mode Google authentication client ID.

2024-04-18 13:38 UTC, panduh-s approved these changes
Works Now

2024-04-18 13:46 UTC, Galeilian approved these changes
gud

2024-04-18 13:46 UTC, merged